name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Install ming64
      run: sudo apt-get install -y mingw-w64
    - name: Build for Linux (x64)
      run: make TARGETOS=LINUX all
    - name: Build for Windows (x64)
      run: make TARGETOS=WIN64 all
    - name: Build for Windows (x86)
      run: make TARGETOS=WIN32 all
    - name: cleanup
      run: make clean
